### ISSUE TITLE
Adapt to Exceptions being thrown in postRead/postWrite

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#130]
Depends on ChimeraTK/DeviceAccess#117
Child of #123

After the changes in ChimeraTK/DeviceAccess#177 the exceptions are not thrown in `doXxxTransferYyy()` anymore, but in `postRead() and postWrite()`. The ExceptionHandlingDecorator is not working any more because it is still trying to catch in the transfers but not in in the post actions. It needs to be adapted accordingly.

The task of this ticket is not to implement the new specification, but to make the ExceptionHandlingDecorator work the same way it did before.

* [ ] change all overloads of doXxxTransfer so they simply call `NDRegisterAccessorDecorator<USER_TYPE>::doXxxTransfer()`. Don't remove them, they will be needed later.
* [ ] rename `ExceptionHandlingDecorator::hasSeenException` to `previousReadFailed`. It has a name conflict with `TransferElement::hasSeenException`.
* Change `genericTransfer()` to `genericPostAction()`. 
  * Remove the whole section `if(!deviceModule.device.isOpened())` (it becomes obsolete with #129))
  * [ ] The `doGenericPostAction()` should look something like this:
```
try{
  callable();
}catch{ChimeraTK::runtime_error &e){
  TransferElement::hasSeenException=true;
  activeException=e;
}
setOwnerValidity(TransferElement::hasSeenException);
if (TransferElement::hasSeenException){
  reportException(activeException.what());
  hasSeenException=false;
  waitForRecovery()
}
```
* [ ] override `doPostRead()` and `doPostWrite()` such that they call  `doGenericPostAction()`
* [ ] add `waitForRecovery()` to `doPreWrite()` (after writing to the recovery accessor, but before calling the inherited `NDRegisterAccessorDecorator<UserType>::doPreWrite()`
* [ ] add an override for `doPreRead()` which does `waitForRecovery()` and then calls  `NDRegisterAccessorDecorator<UserType>::doPreRead()`

* [ ] All tests should now pass again without modification

**Comment by jhktimm** [comment]
Do you realy mean overload doPostRead() and doPostWrite() and that without function arguments?
Or override?
I have th esame question with doPreRead()!?

**Comment by killenb** [comment]
> Do you realy mean overload doPostRead() and doPostWrite() and that without function arguments?
> Or override?
> I have th esame question with doPreRead()!?

 just updated the ticket description. I certainly did mean 'override'

**Comment by jhktimm** [comment]
I also changed in DeviceAccess device_backends/include/TransferElement.h
hasSeenException and activeException from private to protected for this ticket.

**Comment by killenb** [comment]
Blocks #131. Make it readyForImplementation when closing this ticket

**Comment by killenb** [comment]
The idea with the genericPostAction does not work. You need phase 1 of #138

**Comment by killenb** [comment]
> I also changed in DeviceAccess device_backends/include/TransferElement.h
> hasSeenException and activeException from private to protected for this ticket.

Should we take this back? I think there was a reason to have it private and the implementation does not need it.
