### ISSUE TITLE
Introduce `writeWithoutErrorBlocking()` to ExceptionHandlingDecorator

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#134]
Child of #123 
Depends on #130 

**### Original version of the ticket. Needs to be adapted (see comments) ###**

In case of errors, write functions block until the write was successful (waits until the device has recovered). The task of this ticket is to introduce a function which does not block in postRead().

In the ExceptionHandlingDecorator
* [ ] Introduce a boolean flag `dontBlockWritingOnError`. It is false on construction.
* [ ] Change the implementation of doPostWrite(). It should not use the generic implementation any more.
  * Start with the try-catch block which sets hasSeenException and activeException
  * If there was an exception, report it to the DeviceModule
  * If there was an exception and dontBlockOnError is false wait for recovery.
* [ ] Introduce functions `bool writeWithoutErrorBlocking()` and `bool writeDestructivelyWithoutErrorBlocking()`
   * It sets dontBlockWritingOnError true, calls write() or writeDestructively(), and sets the flag back to false.
* [ ] Introduce the functions `bool writeWithoutErrorBlocking()` and `writeDestructivelyWithoutErrorBlocking` in `ScalarAccesspor<T>` and `ArrayAccessor<T>`
  * Dynamic cast _target to ExceptionHandlingDecorator<T>
  * If cast is successful call writeXxxWithoutErrorBlocking()
  * if cast not successful call _target->writeXxx()

Implements https://chimeratk.github.io/ApplicationCore/master/exception_handling_design.html 2.5.2 and 5.1, fixed spec issue 11.14.

The code will be tested when it is used in the TriggerFanOut and ThreadedFanOut (issue #137). No need to write dedicated tests.

**Comment by killenb** [comment]
The dynamic casting only works if the exception handling decorator is the outermost decorator. Find a way to make this work if there is a decorator around it.

**Comment by killenb** [comment]
Idea:
* Extend the ExceptionHandlingDecorator base class with a virtual function `setDontBlockOnError(bool)`.
* The default implementation dynamic cast the target to ExceptionHandlingDecoratorExtended and delegates setDontBlockOnError() if the cast is successful.
* The ExceptionHandlingDecorator then sets its flag.

All decorators must derive from the extended decorator so it is ensured that the ExceptionHandlingDecorator seed it.

The Implementation writeWithoutErrorBlocking() etc in ScalarAccessor and ArrayAccessors try to dynamic cast to the extended accessor, then set flag, call write, unset flag.

The implementation in the ExceptionHandlingDecorator is not needed. It cannot be reached anyway

**Comment by mhier** [comment]
this should now be the behaviour of the normal write. no special function required.

**Comment by killenb** [comment]
writeWithoutErrorBlocking() is not needed in the new concept. This ticket has  become obsolete.
