### ISSUE TITLE
split DeviceModule::reportException

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#135]
Child of #123 

Currently DeviceModule::reportException() does two things:
* It reports the exception to the device module
* It waits until the device has recovered before it returns

The latter is should not always happen according to the new spec, and the  waiting has to happen at a different place.

Task:
* [x] Move the part which is waiting for recovery into a function `void waitForRecovery()`, so reportException 
* [x] In all places where reportException() is now called, add waitForRecovery() after it so the functionality does not change.
* [x] All tests should still work at this point.

The refactoring of the ExceptionHandlingDecorator to correctly use the non-blocking reporting and then wait at a different place will be implemented in tickets #130, #138 and/or #139.

Implementeshttps://chimeratk.github.io/ApplicationCore/master/exception_handling_design.html 4.2.1 and 4.2.2. Resolves specification issue 11.17 and 11.18

**Comment by killenb** [comment]
Fixes spec 11.17 and 11.18

**Comment by jhktimm** [comment]
I think the name waitForException for this function is a mistake here? there is no waiting for it but a report. So I keep reportException(withou waiting for recovery) and add new function waitForRecovery().

**Comment by killenb** [comment]
Fixed it in the descrption

**Comment by jhktimm** [comment]
Äh. How do i close this ticket? I can label it to review...

**Comment by killenb** [comment]
Just close it. I have to check all tickets in closed state anyway.
