### ISSUE TITLE
ThreadedFanout and TriggerFanout should not block

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#137]
Child of #123 
Depends on #134 

The ThreadedFanout and TriggerFanout should not bock if any of its outputs is a broken device.

* [ ] Use writeWithoutErrorBlocking() instead of write(), as introduced in #134.
* [ ] Test for ThreadedFanout: Input from the CS, output to the CS and a device. Use the ExceptionDummy and let it fail. The data should always be updated on the CS.
* [ ] Test for TriggerFanOut: Input from device A, trigger from CS, output to CS and device B. Use the ExceptionDummy for B and let it fail. The data from A should always arrive at the CS.

**Comment by killenb** [comment]
As write operations don't block any more, also the fanouts don't block any more. This ticket has become obsolete.
