### ISSUE TITLE
Make compile again after changes in ChimeraTK::DeviceAccess#116

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#151]
Child of ChimeraTK/ApplicationCore#123
Depends on ChimeraTK/DeviceAccess#116
Depends on ChimeraTK/ControlSystemAdapter#26 (needed to compile)

Adapt to the changes in DeviceAccess:

* ChimeraTK/DeviceAccess#116 introduce API-breaking changes to postRead/Write. Add the new argument to the function overloads. Check Whether the functions should be used (for instance don't generate a new version number in postRead if readTransferLatest did not get new data)

* [x] Extend the API so the code compiles again.
* [ ] Check if you have to adapt functionality
* Check that all tests are still OK.
  * [ ] All existing tests should still pass.
  * [ ] If you had to adapt the functionality check that there is a test for that behaviour

**Comment by killenb** [comment]
Blocks #153. Make 'readyForImplementation' when closing this ticket.

**Comment by phako** [comment]
We have still some issues with tests (like deadlocks), but as discussed that was like that before
