### ISSUE TITLE
Adapt tests to new exception handling scheme

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#155]
Child of #123 

The following tests directly test parts of the exception handling. They need to be checked if they apply to the new specification.

* testDeviceInitialisationHandler
* testExceptionHandling
* testProcessVariableRecovery

What needs to be checked/changed
* [ ] The first read() does not block but returns with DataValidity()::faulty and the previous value. The second read() blocks.

What needs to be extended:
* [ ] readAsync() should now work (blocks like read() on the second time). I think there is no test for it yet.
* [ ] readLatest() and readNonBlocking() should not block. Write new tests for this.
* [ ] write tests for writeNonBlocking() and writeNonBlockingDestructively(). Comment them if they still don't compile, but sketch the test sequence.

**Comment by killenb** [comment]
To make sure we have a sufficient logical coverage there is a new ticket to write systematic tests (#180).

I close this ticket because the existing tests are now all passing, so I consider them as adapted.
