### ISSUE TITLE
Write tests that process variables are re-written to the device after recovery.

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#85]
This is a child of #81 Read that design ticket for more context.
Use the issue81 branch when working on it.

The general route:
* Extend exception dummy to correctly report isFunctional() (probably not even needed)
** If any exception is active, isFunctional() is false
* Write or pick a dummy map file
* Write an ApplicationModule that writes one scalar and one array. Have one input as trigger.
* Connet the device module  to the CS, then connect your application module to the CS.
* Some CS->dev variables should directly go the the device (at least one array, one scalar). the outputs of the module show up as dev->CS.

Check how the tests in testDeviceInitialisationHandler are done. You cannot use the testable mode.
As the process variables are written directly after the initialisation, the concept will be very similar. Maybe even extending those tests with the process variable tests can be a good solution.

Test sequence:
* [x] Start the app and check that the initial values are there.
* [x] Set the exception dummy to throw on write.
* [x] Check that app is in exception state.
* [x] Set all registers in the dummy back to 0.
* [x] Set the exception dummy not to throw. 
* [x] The DeviceModule should recover and the values should be writen to the device.

Take care that you have appropriate timeouts, as we don't have 100 % deterministic behaviour because we use real timing.
