### ISSUE TITLE
Document the recovery mechanism

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#86]
The recovery mechanism has become quite advanced, and there have been many tickets.
This feature set needs to be documented.

There have been two design tickets (#10 and #81) and the implementations in #11, #12, #25, #26, #38, #39, #46, #47, #79 and #84 . The information there should be summarised and documented as separate Doxygen page (or an existing one should be updated/extended).

**Comment by killenb** [comment]
What we need is a specification what the wanted behaviour is. This should be the documentation (maybe not user documentation but developer/implementer documentation and specification).

In addition we need a summary which functionality is implemented.

Tasks:
* [ ] Write up the "wanted behaviour' (documentation)
* [ ] Organise a review if the "wanted behaviour" is what we really need.
* [ ] Write up the implemented behaviour, and compare if it matches the target specification

**Comment by killenb** [comment]
A specification has been written how the error handling is supposed to behave (https://chimeratk.github.io/ApplicationCore/master/exception_handling_design.html).
The specification  page already identifies known issues, where the implementation does not match the requirements. They are collected in the follow-up ticket #123
